###############################################################################
# WILLARD CLIMATE RECONSTRUCTION SHELL SCRIPT
#
# THIS SHELL SCRIPT RUNS SEVERAL R AND PYTHON SCRIPTS IN ORDER TO:
# 
# 1. COMBINE NEW MODERN POLLEN SAMPLES WITH THE NORTH AMERICAN MODERN POLLEN
# 	 DATABASE
# 2. INTERPOLATE CRU TS V4 ONTO NEW MODERN POLLEN SAMPLES
# 3. SPLIT THE EXPANDED NORTH AMERICAN MODERN POLLEN DATABASE INTO NORTHEASTERN
# 	 SOUTHEASTERN, AND EASTERN GROUPS BASED ON SHAPEFILES FROM WILLIAMS AND
#	 SHUMAN (2008, QSR) CORRESPONDING TO THE EXTENTS OF NORTHEASTERN PINUS,
# 	 SOUTHEASTERN PINUS, AND EASTERN PICEA.
# 4. RECONSTRUCT CLIMATE FROM FOSSIL-POLLEN ABUNDANCES FROM THE GREAT DISMAL
# 	 SWAMP CORES.
# 5. PERFORM DIAGNOSTICS ON THE FOSSIL-POLLEN CLIMATE RECONSTRUCTIONS
# 
# AUTHOR: DAVID FASTOVICH, DFASTOVI@SYR.EDU
# DATE: 10.10.2022
###############################################################################

# THIS SCRIPT REQUIRES A SPECIFIC CONDA ENVIRONMENT - THE YAML FILE IS WITHIN
# THE DIRECTORY TO BUILD THIS ENVIRONMENT.
source /opt/miniconda/etc/profile.d/conda.sh
cd ~/Documents/GitHub/Documents/gds_climate_reconstruction
conda activate r-base

# RUN SCRIPTS
Rscript modern_compile.R
python cru_bilinear_interpolate.py
python pollen_split.py
Rscript reconstruction.R
Rscirpt modern_pollen_rda.R